### ISSUE TITLE
int64 with prop_missing > 0 gives error on empty values when synthesizing

### ISSUE THREAD

**Issue by maartenschermer** [sodascience/metasynth#74]
When calling synthesize(), var of type int64 with prop_missing > 0 (details below) sometimes gives:

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

presumably on the missing fields (doesn't happen with prop_missing=0).

{ "name": "Last page", "type": "discrete", "dtype": "int64", "prop_missing": 0.1, "distribution": { "name": "DiscreteUniformDistribution", "parameters": { "low": 6, "high": 7 } } },

**Comment by qubixes** [comment]
I can't reproduce this issue immediately. Can you reproduce it with the advanced tutorial? Or perhaps a self-containing code snippet?

**Comment by maartenschermer** [comment]
Sure, here's a snippet (my notebook is giving a 'builtin' KeyError in get_disttree?):
-------------------
from metasynth import MetaDataset
import pandas as pd

df = pd.DataFrame.from_dict({"bla":{"0":1,"1":1}}, orient="columns")
spec = { "bla": {"prop_missing": 0}}
meta = MetaDataset.from_dataframe(df, spec=spec)
meta.synthesize(10)
# works fine

spec = { "bla": {"prop_missing": 0.99}}
meta = MetaDataset.from_dataframe(df, spec=spec)
meta.synthesize(10)
# generates: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by qubixes** [comment]
@maartenschermer Thanks, I can reproduce it, and I understand why it happens now. I'll have to see whether I can find an easy solution.

**Comment by qubixes** [comment]
This should not be a problem anymore, re-open if this is not the case.
