### ISSUE TITLE
mismatch in behaviour of different RegexDistribution notations

### ISSUE THREAD

**Issue by maartenschermer** [sodascience/metasynth#75]
RegexDistribution(r"[ABCDEF]\d{2,3,5}")
generates
  ValueError: Failed to determine regex from '{2,3,5}'
while
  RegexDistribution([(r"[ABCDEF]",1),(r"\d{2,3,5}",1)])
passes without errors and is transformed to
  [('[ABCDEF]', 1), ('\\d{1,1}', 1)]

**Comment by qubixes** [comment]
Confirmed, the second snippet should also result in an error.
