### ISSUE TITLE
Empty columns lose name in meta dataset

### ISSUE THREAD

**Issue by maartenschermer** [sodascience/metasynth#79]
Dataframe read from CSV, has several empty columns. When generating a meta dataset from the df, all empty columns get an empty name. The column names are imported, as I can address them when specifying a spec for MetaDataset.from_dataframe(), yet they fail to show up in the new meta dataset.

**Comment by qubixes** [comment]
Should be fixed now in the PR. Btw, it seems like you're using pandas for generating the dataset? If so, changing to polars might be a better experience. ;)
