### ISSUE TITLE
Idea: remove some inheritance in favor of decorators

### ISSUE THREAD

**Issue by qubixes** [sodascience/metasynth#95]
One thing that I feel is not quite satisfactory is the multiple inheritance structure in some places of the code. I have read some articles, and perhaps we can do it better with decorators.

```python
def distribution(implements=None, provenance=None, var_type=None, is_unique=None):
    def _wrap(cls):
        if implements is not None:
            cls.implements = implements
#        if provenance is not None:
#            cls.provenance = provenance
        if var_type is not None:
            cls.var_type = var_type
        if is_unique is not None:
            cls.is_unique = is_unique
        return cls
    return _wrap
```

This would be the decorator that you would put in front of the new implementation:

```python
import metasynth as ms

@ms.distribution(implements="core.uniform", var_type="continuous", is_unique=False)
class UniformDistribution(BaseDistribution):
    ...
```

Advantages:

- No multiple inheritance, where the order of the classes matters.
- Can remove the `ContinuousDistribution`, `BaseDisclosure`, etc. classes.
- Possibly easier to understand for developers (perhaps not for beginners?)
- More flexible? I could see a world where the decorator might also register distributions for example.
- Inheritance becomes more optional.

Disadvantages:

- Decorators might be something users don't know about.
- Costs time to implement.

**Comment by vankesteren** [comment]
This sounds pretty good. I think the disadvantage for developers is that it's an extra layer of complexity. (I never really looked into decorators but they look like macros and behave approximately like them). This is definitely a disadvantage, but the cleanness of the code might outweigh the cost 👍 

Do I understand correctly that this would e.g. change the uniform distribution from this:

```python

class UniformDistribution(CoreDistribution, ScipyDistribution, ContinuousDistribution):
    implements = "core.uniform"
    dist_class = uniform # actually, where does this go?

    def __init__(self, min_val: float, max_val: float):
        self.par = {"min_val": min_val, "max_val": max_val}
        self.dist = uniform(loc=self.min_val, scale=max(self.max_val-self.min_val, 1e-8))

    @classmethod
    def _fit(cls, values):
        return cls(values.min(), values.max())

    def _information_criterion(self, values):
        if np.any(np.array(values) < self.min_val) or np.any(np.array(values) > self.max_val):
            return 2*self.n_par + 100*len(values)
        if np.fabs(self.max_val-self.min_val) < 1e-8:
            return 2*self.n_par - 100*len(values)
        return 2*self.n_par - 2*len(values)*np.log((self.max_val-self.min_val)**-1)

    @classmethod
    def default_distribution(cls):
        return cls(0, 1)

    @classmethod
    def _param_schema(cls):
        return {
            "min_val": {"type": "number"},
            "max_val": {"type": "number"},
        }
```

to this:

```python
@ms.distribution(implements="core.uniform", var_type="continuous", is_unique=False)
class UniformDistribution(ScipyDistribution):

    def __init__(self, min_val: float, max_val: float):
        self.par = {"min_val": min_val, "max_val": max_val}
        self.dist = uniform(loc=self.min_val, scale=max(self.max_val-self.min_val, 1e-8))

    @classmethod
    def _fit(cls, values):
        return cls(values.min(), values.max())

    def _information_criterion(self, values):
        if np.any(np.array(values) < self.min_val) or np.any(np.array(values) > self.max_val):
            return 2*self.n_par + 100*len(values)
        if np.fabs(self.max_val-self.min_val) < 1e-8:
            return 2*self.n_par - 100*len(values)
        return 2*self.n_par - 2*len(values)*np.log((self.max_val-self.min_val)**-1)

    @classmethod
    def default_distribution(cls):
        return cls(0, 1)

    @classmethod
    def _param_schema(cls):
        return {
            "min_val": {"type": "number"},
            "max_val": {"type": "number"},
        }
```

**Comment by vankesteren** [comment]
An additional downside: effort to implement this.

**Comment by qubixes** [comment]
The `dist_class` is something specific to distributions based on Scipy, so those would stay the same. But otherwise, yes exactly. The decorator is inherited, so if for example you make a DP version, you only need to change the privacy parameter in the decorator.

This case is quite a simple variant of a decorator, but the idea is that `@f` before some function/class/method will apply the function `f` to it.

If you feel like it might be worth it, I can create a PR for this. I don't think it should be too much work..
