### ISSUE TITLE
Interesting distribution for all_NA variable?

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasynth#98]
`{'name': 'all_NA', 'description': None, 'type': 'string', 'dtype': 'Utf8', 'prop_missing': 1.0, 'distribution': '\\d{3,4}'}`

**Comment by vankesteren** [comment]
is that because it's the default_distribution?

**Comment by qubixes** [comment]
Yes, I suppose so. It could be nice to have a dedicated NA distribution to make it more logical.
